Django/BookAppointment/Cure/urls.py
from django.contrib import admin
from django.urls import path, include
from Services import views

urlpatterns = [
    path('admin/', admin.site.urls),
    #
    path('Services/',include('Services.urls',namespace = 'Services')),

    path('appointment/',views.appointmentList.as_view())


]

Django/BookAppointment/Services/urls.py
from django.contrib import admin
from django.urls import path, include,re_path
from Services import views
app_name='Services'

urlpatterns = [
    re_path(r'^$',views.index,name='index'),

    re_path(r'book-appointment/',views.bookAppointment,\
            name='book_appointment'),
    #services/cardiology
    re_path(r'(?P<category_name>[^%s]*)/',views.serviceInfo,\
          name='service_info')]

Django/BookAppointment/Services/models.py
from django.db import models

# Create your models here.
class Service(models.Model):
    category=models.CharField(max_length=250)
    Fee=models.DecimalField(max_digits=5,decimal_places=2)
    category_pic=models.CharField(max_length=10000)

    def __str__(self):
        return self.category

class Doctor(models.Model):
    service=models.ForeignKey(Service,on_delete=models.CASCADE)
    name=models.CharField(max_length=250)
    qualification=models.CharField(max_length=250)
    experience=models.CharField(max_length=100)
    doctor_pic=models.CharField(max_length=1000)

    def __str__(self):
        return self.name

class Appointment(models.Model):
    doctor=models.ForeignKey(Doctor,on_delete=models.CASCADE)
    patient_name=models.CharField(max_length=250)
    patient_age=models.IntegerField()
    appointment_time=models.DateTimeField(auto_now=False)

    def __str__(self):
        return self.patient_name + ' at ' \
               + str(self.appointment_time) + \
               'with Dr.' +self.doctor.name

Django/BookAppointment/Services/views.py
from django.http import HttpResponse,HttpResponseRedirect
from django.shortcuts import render
from django.template import loader
from django.urls import reverse
from rest_framework.views import APIView
from rest_framework.response import Response
#from services.models import Services
# Create your views here.
from Services.models import Service,Appointment,Doctor
from . serializers import appointmentSerializer


def index(request):
   # html='<h1>Welcome to CURE Hospitals</h1>'
   all_services=Service.objects.all()
   all_doctors=Doctor.objects.all()
   context={'all_services':all_services,'all_doctors':all_doctors
            }
   template=loader.get_template('services/index.html')
   return HttpResponse(template.render(context,request))

def serviceInfo(request,category_name):

   service=Service.objects.get(category=category_name)
   context= {'service':service}
   template=loader.get_template('services/service_info.html')
   return HttpResponse(template.render(context, request))

def bookAppointment(request):
   new_app=Appointment()
   new_app.doctor=Doctor.objects.get(pk=request.POST.get('doctor_name'))
   new_app.appointment_time=request.POST.get('your_time')
   new_app.patient_name=request.POST.get('your_name')
   new_app.patient_age=request.POST.get('your_age')
   new_app.save()
   return HttpResponseRedirect(reverse('Services:index'))

class appointmentList(APIView):
   def get(self,request):
      appointments=Appointment.objects.all()
      serializer=appointmentSerializer(appointments,many=True)
      return Response(serializer.data)

Django/BookAppointment/Services/templates/services/index.html
<h1> Welcome to CURE HOSPITALS</h1>
<br/>
<h3>Below are the services provided by CURE:</h3>

{% if all_services %}
     <ul>

         {% for service in all_services %}
             <li><a href="/Services/{{ service.category }}">
                 {{ service.category }}</a></li>
          {% endfor %}
     </ul>
{% endif %}

<h4>Book Your Appointment</h4>
<form action= "{% url 'Services:book_appointment' %}" method="POST">
    {% csrf_token %}
    <label for="your_name">Your Name:</label>
    <input id="your_name" type="text" name="your_name" value=""><br/>
    <label for="your_age">Your Age:</label>
    <input id="your_age" type="text" name="your_age" value=""><br/>
    <label for="doctor_ame">Doctor Name:</label>

    <select name="doctor_name" id="doctor_ame">
        {% for doctor in all_doctors %}
            <option value="{{ doctor.id }}">{{ doctor.name }} </option>
        {% endfor %}
    </select><br/>


    <label for="your_time">Booking Time:</label>
    <input id="your_time" type="datetime-local" name="your_time" value="{{ timestamp }}">
    <br/><br/>
    <input type="submit" value="Book Appointment">

</form>

Django/BookAppointment/Services/templates/services/service_info.html
<img src="{{ service.category_pic }}">
<h1>{{ service.category }} </h1>
<h3>Fee: {{ service.Fee }} </h3>

<ul>{% for doctor in service.doctor_set.all %}
       <li>Dr. {{ doctor.name }} -- {{ doctor.qualification }} --
         {{ doctor.experience }} </li>
        <img src="{{ doctor.doctor_pic }}" height="62" width="62">
    {% endfor %}
</ul>